/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const Opportunity = IDL.Record({
  'id' : IDL.Nat,
  'remote' : IDL.Bool,
  'barrierLevel' : IDL.Nat,
  'title' : IDL.Text,
  'link' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'score' : IDL.Nat,
  'company' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : IDL.Text,
  'reason' : IDL.Text,
});
export const BuilderMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'role' : IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null }),
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addXerisMiningOpportunity' : IDL.Func([], [], []),
  'appendBuilderMessage' : IDL.Func(
      [
        IDL.Text,
        IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null }),
        IDL.Text,
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBuilderSession' : IDL.Func([], [IDL.Text], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOpportunity' : IDL.Func([IDL.Nat], [Opportunity], ['query']),
  'getSessionMessages' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BuilderMessage)],
      ['query'],
    ),
  'getTotalOpportunityCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listFeaturedOpportunities' : IDL.Func([], [IDL.Vec(Opportunity)], ['query']),
  'listOpportunities' : IDL.Func(
      [IDL.Opt(IDL.Bool), IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Opportunity)],
      ['query'],
    ),
  'listUserSessions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitOpportunity' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const Opportunity = IDL.Record({
    'id' : IDL.Nat,
    'remote' : IDL.Bool,
    'barrierLevel' : IDL.Nat,
    'title' : IDL.Text,
    'link' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'score' : IDL.Nat,
    'company' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : IDL.Text,
    'reason' : IDL.Text,
  });
  const BuilderMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'role' : IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null }),
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addXerisMiningOpportunity' : IDL.Func([], [], []),
    'appendBuilderMessage' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null }),
          IDL.Text,
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBuilderSession' : IDL.Func([], [IDL.Text], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOpportunity' : IDL.Func([IDL.Nat], [Opportunity], ['query']),
    'getSessionMessages' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BuilderMessage)],
        ['query'],
      ),
    'getTotalOpportunityCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listFeaturedOpportunities' : IDL.Func(
        [],
        [IDL.Vec(Opportunity)],
        ['query'],
      ),
    'listOpportunities' : IDL.Func(
        [IDL.Opt(IDL.Bool), IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Opportunity)],
        ['query'],
      ),
    'listUserSessions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitOpportunity' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };