/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BuilderMessage {
  'id' : bigint,
  'content' : string,
  'role' : { 'user' : null } |
    { 'assistant' : null },
  'timestamp' : Time,
}
export interface Opportunity {
  'id' : bigint,
  'remote' : boolean,
  'barrierLevel' : bigint,
  'title' : string,
  'link' : string,
  'createdAt' : Time,
  'description' : string,
  'score' : bigint,
  'company' : string,
  'isFeatured' : boolean,
  'category' : string,
  'reason' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addXerisMiningOpportunity' : ActorMethod<[], undefined>,
  'appendBuilderMessage' : ActorMethod<
    [string, { 'user' : null } | { 'assistant' : null }, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBuilderSession' : ActorMethod<[], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOpportunity' : ActorMethod<[bigint], Opportunity>,
  'getSessionMessages' : ActorMethod<[string], Array<BuilderMessage>>,
  'getTotalOpportunityCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listFeaturedOpportunities' : ActorMethod<[], Array<Opportunity>>,
  'listOpportunities' : ActorMethod<
    [[] | [boolean], [] | [string], [] | [bigint]],
    Array<Opportunity>
  >,
  'listUserSessions' : ActorMethod<[], Array<string>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitOpportunity' : ActorMethod<
    [string, string, string, string, boolean, string, bigint],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];